spring:
  datasource:
    url: jdbc:h2:mem:netflexdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console: 
      enabled: true
      path: /h2
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect