CREATE TABLE users (
  ID INT PRIMARY KEY,
  EMAIL VARCHAR(250) NOT NULL,
  PASSWORD VARCHAR(250) NOT NULL
);

CREATE TABLE userlist (
ID INT PRIMARY KEY,
  EMAIL VARCHAR(250) NOT NULL,
  MOVIEID VARCHAR(250)NOT NULL,
  MOVIEURL VARCHAR(250)NOT NULL,
  MOVIETITLE VARCHAR(250)NOT NULL,
  MOVIENAME VARCHAR(250)NOT NULL,
  MOVIEORIGINALNAME VARCHAR(250)NOT NULL
);
